# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\display_session.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_session_display(object):
    def setupUi(self, session_display):
        session_display.setObjectName("session_display")
        # Adjust the window size to prevent overlapping
        session_display.setMinimumSize(QtCore.QSize(900, 900))  # Increase width and height as needed
        session_display.setMaximumSize(QtCore.QSize(16777215, 16777215))  # Set maximum size to allow scaling
        

        session_display.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.Window)

        # Enable resizing of the window by dragging the edges
        session_display.setAttribute(QtCore.Qt.WA_TranslucentBackground, True)
        session_display.setMouseTracking(True)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(session_display.sizePolicy().hasHeightForWidth())
        session_display.setSizePolicy(sizePolicy)
        session_display.setMinimumSize(QtCore.QSize(600, 1))
        session_display.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        session_display.setFont(font)
        session_display.setWindowTitle("")



        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/DARK-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        session_display.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(session_display)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")

        # Image display setup
        self.image_display = QtWidgets.QLabel(session_display)
        self.image_display.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.image_display.setMinimumSize(QtCore.QSize(1, 1))
        self.image_display.setStyleSheet("background: rgb(0,0,0)")
        self.image_display.setFrameShape(QtWidgets.QFrame.Box)
        self.image_display.setFrameShadow(QtWidgets.QFrame.Plain)
        self.image_display.setText("")
        self.image_display.setScaledContents(False)
        self.image_display.setAlignment(QtCore.Qt.AlignCenter)
        self.image_display.setObjectName("image_display")
        self.verticalLayout.addWidget(self.image_display)

        # Create a wrapper widget for button layout
        self.buttonWidget = QtWidgets.QWidget(session_display)
        self.buttonWidget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.buttonWidget.setContentsMargins(0, 0, 0, 0)
        self.buttonWidget.setObjectName("buttonWidget")
        
        # Grid layout for centering buttons
        self.gridLayout = QtWidgets.QGridLayout(self.buttonWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")

        # Button layout
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setSpacing(0)
        self.buttonLayout.setObjectName("buttonLayout")




        self.session_info = QtWidgets.QLabel(session_display)
        self.session_info.setMinimumSize(QtCore.QSize(70, 21))
        self.session_info.setMaximumSize(QtCore.QSize(70, 21))

        # Create a QFont object with updated settings
        font = QtGui.QFont()
        font.setFamily("Garamond")  # Change font family to Garamond
        font.setPointSize(12)       # Reduce font size to 12
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)

        self.session_info.setFont(font)
        self.session_info.setStyleSheet("color: 'white';")
        self.session_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.session_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.session_info.setLineWidth(1)
        self.session_info.setAlignment(QtCore.Qt.AlignCenter)  # Keeps the text centered
        self.session_info.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.session_info.setObjectName("session_info")
        self.buttonLayout.addWidget(self.session_info)





        # Add buttons to buttonLayout
        self.grid_button = QtWidgets.QPushButton(session_display)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grid_button.sizePolicy().hasHeightForWidth())
        self.grid_button.setSizePolicy(sizePolicy)
        self.grid_button.setMinimumSize(QtCore.QSize(40, 0))
        self.grid_button.setMouseTracking(False)
        self.grid_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.grid_button.setStyleSheet("background: rgb(130, 130, 130);")
        grid_button_icon = QtGui.QIcon()
        grid_button_icon.addPixmap(QtGui.QPixmap(":/icons/icons/grid_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.grid_button.setIcon(grid_button_icon)
        self.grid_button.setIconSize(QtCore.QSize(15, 15))
        self.grid_button.setCheckable(True)
        self.grid_button.setObjectName("grid_button")
        
        self.buttonLayout.setObjectName("horizontalLayout")
        self.buttonLayout.addWidget(self.grid_button)



        self.grayscale_button = QtWidgets.QPushButton(session_display)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grayscale_button.sizePolicy().hasHeightForWidth())
        self.grayscale_button.setSizePolicy(sizePolicy)
        self.grayscale_button.setMinimumSize(QtCore.QSize(40, 0))
        self.grayscale_button.setMouseTracking(False)
        self.grayscale_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.grayscale_button.setStyleSheet("background: rgb(130, 130, 130);")
        icon_grayscale = QtGui.QIcon()
        icon_grayscale.addPixmap(QtGui.QPixmap(":/icons/icons/grayscale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.grayscale_button.setIcon(icon_grayscale)
        self.grayscale_button.setIconSize(QtCore.QSize(15, 15))
        self.grayscale_button.setCheckable(True)
        self.grayscale_button.setObjectName("grayscale")
        
        self.buttonLayout.setObjectName("horizontalLayout")
        self.buttonLayout.addWidget(self.grayscale_button)




        self.lock_scale_button = QtWidgets.QPushButton(session_display)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lock_scale_button.sizePolicy().hasHeightForWidth())
        self.lock_scale_button.setSizePolicy(sizePolicy)
        self.lock_scale_button.setMinimumSize(QtCore.QSize(40, 0))
        self.lock_scale_button.setMouseTracking(False)
        self.lock_scale_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lock_scale_button.setStyleSheet("background: rgb(130, 130, 130);")
        icon_grayscale = QtGui.QIcon()
        icon_grayscale.addPixmap(QtGui.QPixmap(":/icons/icons/lock_scale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.lock_scale_button.setIcon(icon_grayscale)
        self.lock_scale_button.setIconSize(QtCore.QSize(15, 15))
        self.lock_scale_button.setCheckable(True)
        self.lock_scale_button.setObjectName("lock scale")
        
        self.buttonLayout.setObjectName("horizontalLayout")
        self.buttonLayout.addWidget(self.lock_scale_button)


        self.flip_horizontal_button = QtWidgets.QPushButton(session_display)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flip_horizontal_button.sizePolicy().hasHeightForWidth())
        self.flip_horizontal_button.setSizePolicy(sizePolicy)
        self.flip_horizontal_button.setMinimumSize(QtCore.QSize(40, 0))
        self.flip_horizontal_button.setMouseTracking(False)
        self.flip_horizontal_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.flip_horizontal_button.setStyleSheet("background: rgb(130, 130, 130);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/flip horizontal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flip_horizontal_button.setIcon(icon3)
        self.flip_horizontal_button.setIconSize(QtCore.QSize(15, 15))
        self.flip_horizontal_button.setCheckable(True)
        self.flip_horizontal_button.setObjectName("flip_horizontal_button")
        
        self.buttonLayout.setObjectName("horizontalLayout")
        self.buttonLayout.addWidget(self.flip_horizontal_button)







        self.flip_vertical_button = QtWidgets.QPushButton(session_display)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flip_vertical_button.sizePolicy().hasHeightForWidth())
        self.flip_vertical_button.setSizePolicy(sizePolicy)
        self.flip_vertical_button.setMinimumSize(QtCore.QSize(40, 0))
        self.flip_vertical_button.setMouseTracking(False)
        self.flip_vertical_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.flip_vertical_button.setStyleSheet("background: rgb(130, 130, 130);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/flip vertical.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flip_vertical_button.setIcon(icon3)
        self.flip_vertical_button.setIconSize(QtCore.QSize(15, 15))
        self.flip_vertical_button.setCheckable(True)
        self.flip_vertical_button.setObjectName("flip_vertical_button")
        
        self.buttonLayout.setObjectName("horizontalLayout")
        self.buttonLayout.addWidget(self.flip_vertical_button)





        self.previous_image = QtWidgets.QPushButton(session_display)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_image.sizePolicy().hasHeightForWidth())
        self.previous_image.setSizePolicy(sizePolicy)
        self.previous_image.setMinimumSize(QtCore.QSize(40, 0))
        self.previous_image.setMouseTracking(False)
        self.previous_image.setFocusPolicy(QtCore.Qt.NoFocus)
        self.previous_image.setStyleSheet("background: rgb(130, 130, 130);")
        self.previous_image.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/arrow left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_image.setIcon(icon4)
        self.previous_image.setIconSize(QtCore.QSize(15, 15))
        self.previous_image.setObjectName("previous_image")
        self.buttonLayout.addWidget(self.previous_image)




        self.pause_timer = QtWidgets.QPushButton(session_display)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_timer.sizePolicy().hasHeightForWidth())
        self.pause_timer.setSizePolicy(sizePolicy)
        self.pause_timer.setMinimumSize(QtCore.QSize(40, 0))
        self.pause_timer.setMouseTracking(False)
        self.pause_timer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pause_timer.setStyleSheet("background: rgb(130, 130, 130);")
        self.pause_timer.setText("")
        self.pause_timer.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/Pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_timer.setIcon(icon5)
        self.pause_timer.setIconSize(QtCore.QSize(15, 15))
        self.pause_timer.setObjectName("pause_timer")
        self.buttonLayout.addWidget(self.pause_timer)



        self.stop_session = QtWidgets.QPushButton(session_display)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_session.sizePolicy().hasHeightForWidth())
        self.stop_session.setSizePolicy(sizePolicy)
        self.stop_session.setMinimumSize(QtCore.QSize(40, 0))
        self.stop_session.setMouseTracking(False)
        self.stop_session.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stop_session.setStyleSheet("background: rgb(130, 130, 130);")
        self.stop_session.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/Square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_session.setIcon(icon6)
        self.stop_session.setIconSize(QtCore.QSize(15, 15))
        self.stop_session.setObjectName("stop_session")
        self.buttonLayout.addWidget(self.stop_session)




        self.next_image = QtWidgets.QPushButton(session_display)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_image.sizePolicy().hasHeightForWidth())
        self.next_image.setSizePolicy(sizePolicy)
        self.next_image.setMinimumSize(QtCore.QSize(40, 0))
        self.next_image.setMouseTracking(False)
        self.next_image.setFocusPolicy(QtCore.Qt.NoFocus)
        self.next_image.setStyleSheet("background: rgb(130, 130, 130);")
        self.next_image.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/arrow right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_image.setIcon(icon7)
        self.next_image.setIconSize(QtCore.QSize(15, 15))
        self.next_image.setObjectName("next_image")
        self.buttonLayout.addWidget(self.next_image)




        # Copy Image Path Button
        self.copy_image_path_button = QtWidgets.QPushButton(session_display)
        self.copy_image_path_button.setSizePolicy(sizePolicy)
        self.copy_image_path_button.setMinimumSize(QtCore.QSize(40, 0))
        self.copy_image_path_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.copy_image_path_button.setStyleSheet("background: rgb(130, 130, 130);")
        self.copy_image_path_button.setText("Copy Path")
        self.copy_image_path_button.setToolTip("Copy image path to clipboard")
        self.copy_image_path_button.setText("")

        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/copy-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_image_path_button.setIcon(icon9)
        self.copy_image_path_button.setIconSize(QtCore.QSize(15, 15))
        self.copy_image_path_button.setToolTip("Copy image path to clipboard")

        self.buttonLayout.addWidget(self.copy_image_path_button)

        # Open Folder Button
        self.open_folder_button = QtWidgets.QPushButton(session_display)
        self.open_folder_button.setSizePolicy(sizePolicy)
        self.open_folder_button.setMinimumSize(QtCore.QSize(40, 0))
        self.open_folder_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.open_folder_button.setStyleSheet("background: rgb(130, 130, 130);")
        self.open_folder_button.setToolTip("Open folder containing image")
        self.open_folder_button.setText("")

        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/folder-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_folder_button.setIcon(icon10)
        self.open_folder_button.setIconSize(QtCore.QSize(15, 15))

        self.buttonLayout.addWidget(self.open_folder_button)


        # Open settings button
        self.show_main_window_button = QtWidgets.QPushButton(session_display)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_main_window_button.sizePolicy().hasHeightForWidth())
        self.show_main_window_button.setSizePolicy(sizePolicy)
        self.show_main_window_button.setMinimumSize(QtCore.QSize(40, 0))
        self.show_main_window_button.setMouseTracking(False)
        self.show_main_window_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.show_main_window_button.setStyleSheet("background: rgb(130, 130, 130);")
        self.show_main_window_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_main_window_button.setIcon(icon8)
        self.show_main_window_button.setIconSize(QtCore.QSize(15, 15))
        self.show_main_window_button.setToolTip("Show Main Window")

        self.buttonLayout.addWidget(self.show_main_window_button)


        # Delete image
        self.delete_image_button = QtWidgets.QPushButton(session_display)
        self.delete_image_button.setSizePolicy(sizePolicy)
        self.delete_image_button.setMinimumSize(QtCore.QSize(40, 0))
        self.delete_image_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delete_image_button.setStyleSheet("background: rgb(130, 130, 130);")
        self.delete_image_button.setToolTip("Delete current image")
        self.delete_image_button.setText("")

        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/trash-can.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_image_button.setIcon(icon11)
        self.delete_image_button.setIconSize(QtCore.QSize(12, 12))

        self.buttonLayout.addWidget(self.delete_image_button)



        self.timer_display = QtWidgets.QLabel(session_display)
        self.timer_display.setMinimumSize(QtCore.QSize(70, 21))
        self.timer_display.setMaximumSize(QtCore.QSize(70, 21))

        # Create a QFont object with updated settings
        font = QtGui.QFont()
        font.setFamily("Garamond")  # Change font family to Garamond
        font.setPointSize(12)       # Reduce font size to 12
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)

        self.timer_display.setFont(font)
        self.timer_display.setStyleSheet("color: 'white';")
        self.timer_display.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timer_display.setFrameShadow(QtWidgets.QFrame.Plain)
        self.timer_display.setLineWidth(1)
        self.timer_display.setAlignment(QtCore.Qt.AlignCenter)  # Keeps the text centered
        self.timer_display.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.timer_display.setObjectName("timer_display")
        self.buttonLayout.addWidget(self.timer_display)






        self.gridLayout.addLayout(self.buttonLayout, 0, 0, 1, 1, QtCore.Qt.AlignCenter)

        # Add the button widget to the main layout
        self.verticalLayout.addWidget(self.buttonWidget)




        self.retranslateUi(session_display)
        QtCore.QMetaObject.connectSlotsByName(session_display)

    def retranslateUi(self, session_display):
        _translate = QtCore.QCoreApplication.translate

        self.flip_vertical_button.setToolTip(_translate("session_display", "[V] Vertical Flip"))
        self.flip_horizontal_button.setToolTip(_translate("session_display", "[H] Horizontal Flip"))

        self.copy_image_path_button.setToolTip(_translate("session_display", "[C] Copy image path to clipboard"))


        self.show_main_window_button.setToolTip(_translate("session_display", "[Tab] Open settings window"))


        self.open_folder_button.setToolTip(_translate("session_display", "[O] Open image folder"))

        self.grid_button.setToolTip(_translate("session_display", "[G] Toggle grid, [CTRL + G] Grid settings"))
        self.grayscale_button.setToolTip(_translate("session_display", "[F] Toggle grayscale"))
        self.lock_scale_button.setToolTip(_translate("session_display", "[R] Prevent rescaling of the window"))

        self.previous_image.setToolTip(_translate("session_display", "[Left] Previous image"))
        self.previous_image.setShortcut(_translate("session_display", "Left"))
        self.pause_timer.setToolTip(_translate("session_display", "[Space] Pause Timer"))
        self.pause_timer.setShortcut(_translate("session_display", "Space"))



        self.stop_session.setToolTip(_translate("session_display", "[Esc] Stop Session and closes window"))
        self.stop_session.setShortcut(_translate("session_display", "Esc"))


        self.next_image.setToolTip(_translate("session_display", "[Right] Next Image"))
        self.next_image.setShortcut(_translate("session_display", "Right"))

        self.timer_display.setText(_translate("session_display", "00:00"))

